
version: '2.2'

services:

  timescale:
    image: timescale/timescaledb-postgis:${TIMESCALE_VERSION:-1.7.1-pg12}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=*
    volumes:
      - timescale:/data
      - ./db-init:/db-init

  # cube:
  #   image: cubejs/cube:latest
  #   depends_on:
  #     - redis
  #     - timescale
  #   links:
  #     - redis
  #     - timescale
  #   ports:
  #     # It's better to use random port binding for 4000/3000 ports
  #     # without it you will not able to start multiple projects inside docker
  #     # - 4000
  #     # - 3000
  #     # 4000 is a port for Cube.js API
  #     - 4000:4000
  #     # 3000 is a port for Playground web-server
  #     - 3000:3000
  #   env_file: .env
  #   volumes:
  #     # If you are going to use own dependencies, for example axios/vault or anything else for getting configuration
  #     # - .:/cube/conf
  #     - ./dashboard-app:/cube/conf/dashboard-app
  #     - ./cube.js:/cube/conf/cube.js
  #     - ./schema:/cube/conf/schema

  redis:
    image: redis:6
    restart: always

volumes:
  timescale:
